# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TrashMob Pull Request Build

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.x'  # set this to the dotnet version to use
  DOTNET_VERSION2: '6.0.x'  # set this to the dotnet version to use
  CONFIGURATION: Release

jobs:
  prep:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup DotNet ${{ env.DOTNET_VERSION2 }} Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION2 }}

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

  buildWebapp:
    runs-on: windows-latest
    needs: prep

    steps:
    - name: Build Web App
      run: dotnet build TrashMob\TrashMob.csproj --configuration ${{ env.CONFIGURATION }}

    - name: Publish Web App
      run: dotnet publish TrashMob\TrashMob.csproj --configuration ${{ env.CONFIGURATION }} -o ${{env.DOTNET_ROOT}}/mywebapp

  buildFunctionApp:

    runs-on: windows-latest
    needs: prep

    steps:
    - name: Build Function App
      run: dotnet build TrashMobJobs\TrashMobJobs.csproj --configuration ${{ env.CONFIGURATION }}

    - name: Publish Function App
      run: dotnet publish TrashMobJobs\TrashMobJobs.csproj --configuration ${{ env.CONFIGURATION }} -o ${{env.DOTNET_ROOT}}/myfunctionapp


  buildMobileApp:
    runs-on: windows-latest
    needs: prep

    steps:
    - name: Build Mobile App
      run: dotnet build TrashMobMobileApp\TrashMobMobileApp.csproj --configuration ${{ env.CONFIGURATION }}

    - name: Publish Mobile App
      run: dotnet publish TrashMobMobileApp\TrashMobMobileApp.csproj --configuration ${{ env.CONFIGURATION }} -o ${{env.DOTNET_ROOT}}/mymobileapp
