# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: TrashMob Mobile App Pull Request Build

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'IEFPolicies/**'
 
env:
  DOTNET_VERSION: '7.0.x'  # set this to the dotnet version to use
  DOTNET_VERSION2: '7.0.x'  # set this to the dotnet version to use
  CLIENT_SECRET: $(secrets.IEF_POLICY_UPDATE_CLIENT_SECRET)
  CLIENT_ID: 'e75e0bf9-aa83-4d06-a60e-89f4b29db739'
  TENANT_NAME: 'TrashMobDev'

jobs:
  DeployIEF:
    runs-on: windows-latest
    environment: test
    name: IEF Deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Powershell
        run: |
          Install-Module -Name IefPolicies -Scope CurrentUser -Force -AllowPrerelease
          Connect-IefPolicies -tenant ${env:TENANT_NAME} -clientId ${env:CLIENT_ID} -clientSecret ${env:CLIENT_SECRET}
          Import-IefPolicies -sourceDirectory "./../../IEFPolicies" -configurationFilePath "./../../IEFPolicies/trashmobdev.json"
